from http.server import HTTPServer, BaseHTTPRequestHandler
from urllib.parse import urlparse, parse_qs
import predictUserInput as nn

def content(query):
    print("Running content generation function", str(query))
    if query.get("p"):
        res = nn.predictUserHealth([float(x) for x in query.get("p")[0].split(",")])
        print("Returning", res)
    else:
        print("No Query Parameter Found")
        res = "No Query Parameter Found"
    return res

# HTTP Server, responding to GET requests with content generated by the 'content' function
class CloudHTTPRequestHandler(BaseHTTPRequestHandler):

    def do_GET(self):
        self.send_response(200)
        self.end_headers()
        queryString = parse_qs(urlparse(self.path).query)
        self.wfile.write(str(content(queryString)).encode())

if __name__=="__main__":
    print("Started Server")
    httpd = HTTPServer(('0.0.0.0', 8080), CloudHTTPRequestHandler)
    httpd.serve_forever()
